"use client";

import { useEffect, useMemo, useState } from "react";
import {
  CalendarDays,
  CheckCircle2,
  Clock3,
  Plus,
  RefreshCcw,
  Sparkles,
} from "lucide-react";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

type Task = {
  id: string;
  title: string;
  description?: string;
  status: "todo" | "in_progress" | "done";
  priority: "low" | "medium" | "high";
  dueDate?: string;
  source: "agent" | "manual";
  sourceMessage?: string;
};

type DailyPlan = {
  id: string;
  date: string;
  title: string;
  summary: string;
  items: Array<{
    taskId: string;
    title: string;
    priority: "low" | "medium" | "high";
    status: "todo" | "in_progress" | "done";
    dueDate?: string;
    slot: string;
    rationale: string;
  }>;
  createdAt: string;
};

export function TasksBoard() {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [dailyPlan, setDailyPlan] = useState<DailyPlan | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingPlan, setIsGeneratingPlan] = useState(false);
  const [notice, setNotice] = useState("");

  async function loadTasks() {
    setIsLoading(true);

    try {
      const response = await fetch("/api/tasks", { cache: "no-store" });

      if (!response.ok) {
        throw new Error("Failed to load tasks.");
      }

      const data = (await response.json()) as { tasks: Task[] };
      setTasks(data.tasks);
    } finally {
      setIsLoading(false);
    }
  }

  async function loadDailyPlan() {
    const response = await fetch("/api/daily-plan", { cache: "no-store" });

    if (!response.ok) {
      return;
    }

    const data = (await response.json()) as { plan: DailyPlan | null };
    setDailyPlan(data.plan);
  }

  async function generateDailyPlan() {
    setIsGeneratingPlan(true);
    setNotice("");

    try {
      const response = await fetch("/api/daily-plan", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({}),
      });

      if (!response.ok) {
        setNotice("今日计划生成失败。");
        return;
      }

      const data = (await response.json()) as { plan: DailyPlan };
      setDailyPlan(data.plan);
      setNotice("今日计划已生成并保存。");
    } finally {
      setIsGeneratingPlan(false);
    }
  }

  useEffect(() => {
    loadTasks();
    loadDailyPlan();
  }, []);

  const groups = useMemo(() => buildGroups(tasks), [tasks]);

  return (
    <>
      <div className="flex items-center justify-between gap-4 border-b border-white/10 px-6 py-4">
        <div className="flex flex-wrap gap-2">
          {["All", "High", "Today", "Generated by Agent"].map((filter) => (
            <Badge
              key={filter}
              variant="outline"
              className="rounded-full border-white/10 bg-white/[.045] px-3 py-1.5 text-[#a8adba]"
            >
              {filter}
            </Badge>
          ))}
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={loadTasks}
            className="rounded-[14px] border-white/10 bg-white/[.045] text-[#f3f0e8] hover:bg-white/[.075]"
          >
            <RefreshCcw className="h-4 w-4" />
            刷新
          </Button>
          <Button
            onClick={generateDailyPlan}
            disabled={isGeneratingPlan}
            className="rounded-[14px] bg-gradient-to-br from-[#7dd3c7] to-[#d9f99d] font-bold text-[#111318] hover:brightness-105"
          >
            <Plus className="h-4 w-4" />
            {isGeneratingPlan ? "生成中" : "生成今日计划"}
          </Button>
        </div>
      </div>

      <div className="p-6">
        <Card className="mb-5 rounded-[22px] border-white/10 bg-white/[.055] text-[#f3f0e8]">
          <CardContent className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_280px]">
            <div>
              <div className="flex items-center gap-2 text-sm font-semibold">
                <Sparkles className="h-4 w-4 text-[#7dd3c7]" />
                Agent Task Plan
              </div>
              <p className="mt-2 max-w-2xl text-sm leading-6 text-[#a8adba]">
                这里读取真实任务数据。你在 Chat 里说“明天下午提醒我整理项目计划”，Agent
                会调用 createTask；你问“今天我该做什么”，Agent 会调用 generateDailyPlan。
              </p>
              {notice ? (
                <div className="mt-3 rounded-[14px] border border-white/10 bg-white/[.045] px-3 py-2 text-sm text-[#a8adba]">
                  {notice}
                </div>
              ) : null}
            </div>
            <div className="grid grid-cols-3 gap-3 text-center">
              <Metric label="Open" value={String(countOpen(tasks))} />
              <Metric label="Agent" value={String(countAgent(tasks))} />
              <Metric label="Done" value={String(countDone(tasks))} />
            </div>
          </CardContent>
        </Card>

        <DailyPlanCard plan={dailyPlan} onGenerate={generateDailyPlan} isGenerating={isGeneratingPlan} />

        <Accordion
          type="multiple"
          defaultValue={["todo", "in_progress"]}
          className="grid gap-4"
        >
          {groups.map((group) => (
            <AccordionItem
              key={group.value}
              value={group.value}
              className="overflow-hidden rounded-[22px] border border-white/10 bg-white/[.045] px-0"
            >
              <AccordionTrigger className="px-5 py-4 text-left hover:no-underline">
                <div className="flex min-w-0 flex-1 items-center gap-4">
                  <div
                    className={`h-11 w-1.5 rounded-full bg-gradient-to-b ${group.accent}`}
                  />
                  <div className="min-w-0">
                    <div className="flex flex-wrap items-center gap-3">
                      <span className="text-base font-semibold">
                        {group.title}
                      </span>
                      <Badge
                        variant="outline"
                        className="rounded-full border-white/10 text-[#a8adba]"
                      >
                        {group.tasks.length} tasks
                      </Badge>
                    </div>
                    <p className="mt-1 text-sm text-[#a8adba]">
                      {group.summary}
                    </p>
                  </div>
                </div>
              </AccordionTrigger>
              <AccordionContent className="px-5 pb-5">
                <div className="grid gap-3">
                  {group.tasks.map((task) => (
                    <TaskRow key={task.id} task={task} />
                  ))}
                  {group.tasks.length === 0 ? (
                    <div className="rounded-[16px] border border-dashed border-white/10 p-5 text-sm text-[#777f90]">
                      {isLoading ? "加载任务中..." : "这个分组还没有任务。"}
                    </div>
                  ) : null}
                </div>
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </>
  );
}

function DailyPlanCard({
  plan,
  onGenerate,
  isGenerating,
}: Readonly<{
  plan: DailyPlan | null;
  onGenerate: () => void;
  isGenerating: boolean;
}>) {
  return (
    <Card className="mb-5 rounded-[22px] border-white/10 bg-white/[.055] text-[#f3f0e8]">
      <CardContent className="p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-sm font-semibold">
              <CalendarDays className="h-4 w-4 text-[#7dd3c7]" />
              今日计划
            </div>
            <p className="mt-2 text-sm leading-6 text-[#a8adba]">
              {plan?.summary ?? "还没有生成计划。会基于当前未完成任务排序并保存结果。"}
            </p>
          </div>
          <Button
            type="button"
            onClick={onGenerate}
            disabled={isGenerating}
            variant="outline"
            className="rounded-[14px] border-white/10 bg-white/[.045] text-[#f3f0e8] hover:bg-white/[.075]"
          >
            <RefreshCcw className="h-4 w-4" />
            {isGenerating ? "生成中" : plan ? "重新生成" : "生成"}
          </Button>
        </div>

        {plan ? (
          <div className="mt-4 grid gap-3">
            <div className="flex flex-wrap items-center gap-2 text-xs text-[#777f90]">
              <Badge variant="outline" className="rounded-full border-white/10 text-[#a8adba]">
                {plan.date}
              </Badge>
              <span>保存于 {new Date(plan.createdAt).toLocaleString()}</span>
            </div>
            {plan.items.length > 0 ? (
              plan.items.map((item) => (
                <div
                  key={`${plan.id}-${item.taskId}`}
                  className="grid gap-3 rounded-[16px] border border-white/10 bg-[#111319]/70 p-4 md:grid-cols-[80px_1fr_auto]"
                >
                  <div className="text-sm font-semibold text-[#7dd3c7]">
                    {item.slot}
                  </div>
                  <div>
                    <div className="text-sm font-semibold">{item.title}</div>
                    <div className="mt-1 text-xs leading-5 text-[#a8adba]">
                      {item.rationale}
                    </div>
                  </div>
                  <Badge
                    variant="outline"
                    className="h-fit rounded-full border-white/10 text-[#a8adba]"
                  >
                    {item.priority}
                  </Badge>
                </div>
              ))
            ) : (
              <div className="rounded-[16px] border border-dashed border-white/10 p-5 text-sm text-[#777f90]">
                暂无可安排任务。
              </div>
            )}
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}

function TaskRow({ task }: Readonly<{ task: Task }>) {
  return (
    <div className="grid gap-4 rounded-[16px] border border-white/10 bg-[#111319]/70 p-4 md:grid-cols-[1fr_auto]">
      <div>
        <div className="flex items-center gap-2 text-sm font-semibold">
          {task.status === "done" ? (
            <CheckCircle2 className="h-4 w-4 text-[#a3e635]" />
          ) : (
            <Clock3 className="h-4 w-4 text-[#f6c76f]" />
          )}
          {task.title}
        </div>
        <p className="mt-2 text-sm leading-6 text-[#a8adba]">
          {task.description || task.sourceMessage || "由 Agent 工具调用创建。"}
        </p>
        <p className="mt-2 text-xs text-[#777f90]">
          来源：{task.source === "agent" ? "Agent createTask" : "Manual"}
        </p>
      </div>
      <div className="flex items-start gap-2 md:justify-end">
        <Badge
          variant="outline"
          className="rounded-full border-white/10 text-[#a8adba]"
        >
          {task.priority}
        </Badge>
        <Badge
          variant="outline"
          className="gap-1 rounded-full border-white/10 text-[#a8adba]"
        >
          <CalendarDays className="h-3.5 w-3.5" />
          {task.dueDate ?? "未设置"}
        </Badge>
      </div>
    </div>
  );
}

function Metric({ label, value }: Readonly<{ label: string; value: string }>) {
  return (
    <div className="rounded-[16px] border border-white/10 bg-[#111319]/70 p-3">
      <div className="text-lg font-semibold">{value}</div>
      <div className="text-xs text-[#a8adba]">{label}</div>
    </div>
  );
}

function buildGroups(tasks: Task[]) {
  return [
    {
      value: "todo",
      title: "Todo",
      summary: "Agent 创建后等待执行的任务",
      accent: "from-[#7dd3c7] to-[#d9f99d]",
      tasks: tasks.filter((task) => task.status === "todo"),
    },
    {
      value: "in_progress",
      title: "In Progress",
      summary: "正在推进的任务",
      accent: "from-[#b8a1ff] to-[#7dd3c7]",
      tasks: tasks.filter((task) => task.status === "in_progress"),
    },
    {
      value: "done",
      title: "Done",
      summary: "已经完成的任务",
      accent: "from-[#a3e635] to-[#7dd3c7]",
      tasks: tasks.filter((task) => task.status === "done"),
    },
  ];
}

function countOpen(tasks: Task[]) {
  return tasks.filter((task) => task.status !== "done").length;
}

function countDone(tasks: Task[]) {
  return tasks.filter((task) => task.status === "done").length;
}

function countAgent(tasks: Task[]) {
  return tasks.filter((task) => task.source === "agent").length;
}
